### PR TITLE
Implemented Builder Pattern for creating classBox's

### PR DESCRIPTION
**Pull request by Lantzer**
## mainDiagramController.java
- Uses ClassBoxBuilder to build a classBox with the specified Pane's added.

## ClassBox.java
- Added Rectangle[] ranchors to the constructor and sets the class level variable to the passed in array.
- added setDragBox(VBox) setter method so we can set the dragBox class level variable from outside  of the class.
- Added nameAndDelete(String) method where we take in a className and return an HBox that has a name label, seperator, and a created deleteButton inside of it.
- Set createFieldPane and createMethodPane to public so that we can call them from the ClassBoxBuilder.java

## ClassBoxBuilder.java
- Builder display pattern, we have a base constructor, and helper methods to add to the base ClassBoxBuilder object
- setup() setups up the initial structure of the classBox, including the setup for the relationship anchors. Returns the vbase object that holds all of the contents
- withFieldPane()/withMethodPane() which sets their respective boolean to true.
- build() creates a generic ClassBox item, adds a nameAndDelete HBox with the passed in className to it and sets it as a child of the VBox object inside of the content box that is now inside of the classBox. 
- we then go through the if statements where it adds fields/method panes if they were wanted.

### CODE REVIEW

**Comment by RyanHirte** [comment]
Don't we need to implement an interface for builders and then the builder would implement that interface?

**Comment by RyanHirte** [comment]
Patterns.txt was never updated to justify how this is builder or the files/line numbers.

**Comment by RyanHirte** [comment]
There isn't much documentation

**Comment by RyanHirte** [comment]
No unit tests.

**Comment by tharium** [comment]
Looks good

**Pull request merged**
