### PR TITLE
Save load dialogs

### PR DESCRIPTION
**Pull request by coreybasden**
save now simply saves to whatever file was most recently loaded or saved. if none exists yet it calls save as. save as shows proper file selector dialog box. so does load. load recent menu works now but its an illusion. its not actually your most recent files its just a list of all save files currently in the directory. it will work for now.

### CODE REVIEW

**Comment by RyanHirte** [comment]
Are there unit tests?

**Comment by coreybasden** [comment]
> Are there unit tests?

Forgot about that! I'll have them done tonight.

**Comment by RyanHirte** [comment]
Can we remove the saved files (t1, t54)? I feel like those shouldn't be in the project if we don't need them. Were they only used for testing? Also the documentation isn't super clear in Data.java for the saving stuff or why we need the equals method etc. For people like us who have been working on the project this whole time the code might make sense, but let's say someone else joins and reads that they might not have a clue why or what those methods do or the point of them you know?

**Comment by coreybasden** [comment]
Yea save files, as has always been the case this quarter, are never needed. Our gitignore hasn't worked perfectly since day one. And as for the equals method it's a common tactic used all the time to assist in unit testing but I'll add some comments anyway.

**Pull request closed without merging**
